from . import mail_channel
from . import quotation_queue
from . import quotation
from . import project_request
from . import routes
from . import mail_gateway_whatsapp
from . import mail_gateway_whitelist
from . import mail_gateway_whitelist_contact
from . import res_partner
from . import whatsapp_cache_notifier
from . import learned_alias
